### ISSUE TITLE
Please update to use @prisma/client@4.0.0

### ISSUE THREAD

**Issue by e23thr** [unlight/prisma-graphql-type-decimal#8]
I cannot install this package with errors below

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: orange-production-api@0.0.1
npm ERR! Found: @prisma/client@4.9.0
npm ERR! node_modules/@prisma/client
npm ERR!   @prisma/client@"^4.8.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @prisma/client@"3 4" from prisma-graphql-type-decimal@2.0.5
npm ERR! node_modules/prisma-graphql-type-decimal
npm ERR!   prisma-graphql-type-decimal@"2.0.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by unlight** [comment]
Please, try install latest version 2.0.6
