### ISSUE TITLE
Getting empty Decimal property

### ISSUE THREAD

**Issue by uncleDimasik** [unlight/prisma-graphql-type-decimal#9]
It's not an issue!!! Just a tip.
If you use this package with  "prisma-nestjs-graphql" codegen and  "class-validator", add the "transform: true" option to the validation configuration.

my nestjs example
```typescript
  app.useGlobalPipes(
    new ValidationPipe({
      enableDebugMessages: isDevelopment,
      skipUndefinedProperties: true,
      transform: true, // !!! important
    }),
  );
``` 

P.S. 
I lost 5 hours on this

**Comment by unlight** [comment]
It`s enabled by default.
